### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by probonopd** [The-Jonsey/streamdeck-editor#1]
Unhandled exception occurs when running without internet access (in a Firejail sandbox):

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/6f799d40e7de4cd06b5f9345f1396bd137bcf6be/database/Streamdeck_Editor/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1934

**Comment by The-Jonsey** [comment]
That's not trying to access the internet, that's trying to access a DBus interface, namely the DBus interface created by [this](https://github.com/The-Jonsey/streamdeckd), if you're going to create an issue, please RTFM first, namely:

`Make sure the daemon is running, by running streamdeckd, then run the editor by running the AppImage.`

**Comment by probonopd** [comment]
Thanks for the clarification. :+1: 

However, the philosophy behind AppImage is that you can just download it, and run it, without having to install or run anything else first.

So, would it be a good idea to ship the `streamdeckd` daemon inside the AppImage, and launch it before executing the editor automatically?

Thank you for your consideration.

**Comment by The-Jonsey** [comment]
No, because the idea was that the daemon would run without anything superfluous, so it would use as little system resources as possible, and be detached so anyone could create their own editor, packaging them together sort of defeats the point of that. 

Thanks for the consideration for putting the editor into AppImageHub, but in this case, I don't think it would be a good fit.
